- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - railwaycat/emacsmacport
    homebrew_packages:
      - { name: git }
      - { name: emacs }
      - { name: zsh }
      - { name: zsh-completions }
    homebrew_cask_packages:
      - { name: iterm2 }
      - { name: firefox }
      - { name: google-chrome }
      - { name: java }
      - { name: skype }
      - { name: slack }
      - { name: sourcetree }
      - { name: flux }
      - { name: atom }
      - { name: virtualbox }
      - { name: dropbox }
      - { name: google-japanese-ime }
      - { name: adobe-creative-cloud }
      - { name: adobe-illustrator-cc }
      - { name: adobe-photoshop-cc }
      - { name: adobe-photoshop-lightroom }
      - { name: adobe-reader }
      - { name: evernote }

  tasks:
    - include: tasks/brew_tap.yml
    - include: tasks/brew_install.yml
    - include: tasks/brew_cask_install.yml
    - include: tasks/zsh.yml

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
